### ISSUE TITLE
Issue with using the map

### ISSUE THREAD

**Issue by Kreuger** [pnoll1/osmand_map_creation#17]
Hey I recently got a new phone so I had to download the map again. However when I try to open it with OSMAnd, I get an error as you can see in my screenshot.
![Screenshot_20210324-182221](https://user-images.githubusercontent.com/42020/112769158-9719be80-8fed-11eb-9708-ca0a5abc8391.jpg)

Im using the 0.7 release and the map is for Ontario Canada. Using Android 10 and OSMAnd 3.9.10.

**Comment by Kreuger** [comment]
I just tried 0.7.2 which I should have done from the start and it worked. This can be closed.

**Comment by pnoll1** [comment]
Did you use the 0.7 file before and it worked?

Maybe an incomplete download since the file is over 1GB.

**Comment by Kreuger** [comment]
Yeah it definitely worked on my previous phone. I just disnt realize the newer version included Canada as well. I just grabbed the O Canada release.

**Comment by pnoll1** [comment]
I confirmed 0.7 file still works with 3.9.10. Assuming issue with incomplete or invalid download that will be mitigated by adding hashs to confirm downloads.
