### ISSUE TITLE
Australia au/countrywide

### ISSUE THREAD

**Issue by dugite-code** [pnoll1/osmand_map_creation#29]
I've been trying to figure out how to generate a map with the openaddresses au/countrywide address set (Addresses are generated for the Australian Government but not licensed appropriately for openstreetmaps). I'm not sure where to begin

Looking at the processing.sh I'm presuming I would end up with a command similar to this?
```
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py au:act au:nsw au:vic au:qld au:tas au:nt au:sa au:wa --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
```

https://results.openaddresses.io/sources/au/countrywide
https://download.geofabrik.de/australia-oceania/australia.html

**Comment by dugite-code** [comment]
Awesome thanks for the info, I'll try look into that this weekend

**Comment by dugite-code** [comment]
Awesome, Thanks. I was having quite a bit of trouble getting it built myself

**Comment by pnoll1** [comment]
Successfully built again this month. Feel free to open an issue if you have problems or questions.
