### ISSUE TITLE
No Massachusetts file?

### ISSUE THREAD

**Issue by joshbowyer** [pnoll1/osmand_map_creation#35]
There is no obf available at opensupermaps.com for Massachusetts...

**Comment by pnoll1** [comment]
This was intentional from way back before I was using Open Addresses. I forgot to add it back since then.

Anyway, I added it to the build list. I just started builds, so check back on the 26th.

**Comment by pnoll1** [comment]
File is up: https://opensupermaps.com/static/downloads/Us_ma.obf
