### ISSUE TITLE
ODBL Link is Outdated

### ISSUE THREAD

**Issue by h4xor666** [pnoll1/osmand_map_creation#43]
The ODBL link on the overview is out of date, I believe this is the new link for it: https://opendatacommons.org/licenses/odbl/

**Comment by h4xor666** [comment]
Actually, here's a direct link to the actual text of the license if you wanna use that: https://opendatacommons.org/licenses/odbl/1-0/

**Comment by pnoll1** [comment]
fixed in 1cfb02b0f3218c1e9b4a6427c9e43f70ea77113f
