### ISSUE TITLE
Only a handful of addresses show up after import into OsmAnd

### ISSUE THREAD

**Issue by bhankerson** [pnoll1/osmand_map_creation#67]
Hi, please forgive me if this is an ignorant question, but I've searched and not found an answer. I downloaded Us_mn.obf to my android phone, opened it with OsmAnd, it loaded for a while, then opened, I disabled the "United States Minnesota" map, so only "Us mn" was active. OSM map was there (good), and some addresses were new (good), but I quickly found out that there were not many new addresses (bad). I downloaded a collection from [OpenAddresses](https://batch.openaddresses.io/data) in order to explore it in QGIS. If all of those addresses are supposed to be in the Us_mn.obf map, something is going wrong, only a very small percentage of the addresses are actually showing up on my map (and in my search).
Could someone give me some guidance on how to fix this problem? Have I done something stupid in my import process? "United States Minnesota" is still installed, but deactivated, might I actually need to delete it? I'm afraid I'll lose one of my free downloads if I do.
Thank you for any help!
Brett

**Comment by pnoll1** [comment]
It sounds like you loaded the map properly.

The script filters bad data from OA so it could be that all those extra addresses were filtered. I’ll check the build logs to see.

**Comment by bhankerson** [comment]
Ok, thank you! Do you have your OpenSuperMaps map available online somewhere, so I can see what it should look like?

**Comment by pnoll1** [comment]
Unfortunately, no, that would be another piece of software to setup.

Logs show several counties had large amounts of data missing address numbers. Some examples:
- isanti: 7218
- itasca: 50552
- cook: 6870
- clay: 34068
- koochiching: 48970
- st louis: 104041

It looks like OA has a lot of bad data that had to be dropped.  Build log is attached if you want to look.  
[processing_2022-11-21T03:14:12.063863.log](https://github.com/pnoll1/osmand_map_creation/files/10293543/processing_2022-11-21T03.14.12.063863.log)

**Comment by bhankerson** [comment]
Thank you for looking into it. What causes data to be "bad"? Is there a way to fix it, or is that just the way it is until the OA features get repaired/updated?

**Comment by bhankerson** [comment]
I noticed with the December map that the set of addresses that show up (are "good") is different than November's, some disappeared, while others are new

**Comment by pnoll1** [comment]
Some data is bad at the source. 
I’m guessing OA scrapers sometimes break and don’t grab all the data.

If OA data is the problem, you can check the data at the source to see if it’s the problem or if it’s OA scraping.

**Comment by bhankerson** [comment]
I have the source data from OA (as a geojson file), how do I tell if that's where the problem is? Plenty of addresses look to be complete, but aren't showing up on OsmAnd. I'm sorry, I don't know how to troubleshoot this kind of thing

**Comment by bhankerson** [comment]
Is there anything I can do to fix this? This month's isn't any better. Is this an OA problem, that I should be opening an issue with them?

**Comment by pnoll1** [comment]
Sorry for the delay, I missed the message on 12/30.

Please post examples of data from OA that you think should be in the final file but isn't.

**Comment by bhankerson** [comment]
I'm not sure exactly how you want the examples, but here is a shapefile of Faribault County. I have removed all the "bad" data points, so that it is made up entirely of the points that have a number, street, city, and postcode (there are four without a postcode). I attach a closeup of Bass Lake, as it appears on OsmAnd Us_mn.obf, and the OA point file overlayed onto Bing Satellite
[FaribaultCo.zip](https://github.com/pnoll1/osmand_map_creation/files/10542299/FaribaultCo.zip)
![image](https://user-images.githubusercontent.com/33230497/215653642-7403f095-6429-4978-9ddd-3abf73a6dcdb.png)
![Bass Lake](https://user-images.githubusercontent.com/33230497/215653680-71983414-8176-4796-b3ba-217aa23a0ba6.jpg)

**Comment by pnoll1** [comment]
- [x] In OA data
- [x] loaded in database
- [x] output to osm address file
- [ ] In state pbf file
- [ ] In obf file

I'll need to finish this up later. There's either an issue merging into state file or with osmand map creator.

**Comment by bhankerson** [comment]
Thank you! If there's anything I can do to help, please let me know. I don't know my way around GitHub, but I can work with shapefiles in QGIS. Will fixing this issue solve the problem of the missing addresses in the other MN counties as well?

**Comment by zyphlar** [comment]
I have this situation in Oregon (only a few addresses present) and also the most recent files from January on the website don't load at all. (Oregon is blank, while I tested DC and it worked)

**Comment by pnoll1** [comment]
@bhankerson too early to tell. I still need to go through build files to find where error happened.

@zyphlar example addresses please. Also, make sure the file is complete using checksum.

**Comment by pnoll1** [comment]
@zyphlar I just downloaded Oregon from opensupermaps.com and it loaded fine. Double check that checksum. 

@zyphlar @bhankerson if you have time please try out your respective files from [0.95 release](https://github.com/pnoll1/osmand_map_creation/releases/tag/0.95).  Files for both states got ~20% smaller the next release. I'm not sure if it's related, but the size change is a big red flag.

**Comment by Ruthalas** [comment]
I believe us_wa is also effected.
It dropped from ~750MB in the .95 release to ~550MB in the .96 release.
I can visually note a lack of address numbers looking at the map loaded into OSMAnd.
.95 works, while subsequent releases cannot find addresses when using address numbers.

(I wondered why specifying addresses had stopped working, and came to find this thread, which appears to match my experience.)

**Comment by bhankerson** [comment]
> @zyphlar I just downloaded Oregon from opensupermaps.com and it loaded fine. Double check that checksum.
> 
> @zyphlar @bhankerson if you have time please try out your respective files from [0.95 release](https://github.com/pnoll1/osmand_map_creation/releases/tag/0.95). Files for both states got ~20% smaller the next release. I'm not sure if it's related, but the size change is a big red flag.

Yes, haha! Look at all those addresses :) The 0.95 release is good for MN. So now all that's left is to figure out what changed, and repair it?

**Comment by pnoll1** [comment]
Issue is actually in output_osm stage. In 2001e75aa46c2b63d5eb5e15c8cb7eb286b333c3, I used the id variable instead of id_start. This lead to each source file having same osm ids and merging over each other.

I'll fix this and add a unit test this weekend. Fix will be in this months release.

**Comment by bhankerson** [comment]
Awesome, looking forward to it! Thanks for fixing this

**Comment by pnoll1** [comment]
fixed in 2c30cb028b7e6ae76ee0bada9ea7b31b4cef23cd.

@bhankerson please try out https://opensupermaps.com/static/downloads/Us_mn.obf. File size looks right(couple MBs bigger than 0.95) and test addresses around Bass lake show up. It wouldn't load on iOS, but it's working on Android.

note for me: test address was 4 North Shore Dr Winnebago

**Comment by bhankerson** [comment]
Wow, it's everything I've ever dreamed of! Thank you very much! Now to get more counties in OpenAddresses

**Comment by pnoll1** [comment]
New files are up. Closing this out.
