### ISSUE TITLE
Request: France

### ISSUE THREAD

**Issue by edgar-vincent** [pnoll1/osmand_map_creation#69]
Hello!

I'm very glad I've stumbled upon this project. I've been struggling with Osmand's address lookups, and this looks perfect.
Do you think it would be possible to add support for France? I'd be glad to provide some testing.

Thanks a lot!

**Comment by pnoll1** [comment]
It'll probably be a few days+ for this. 

Notes: 
- France likely too big to build as one piece
- French subdivions missing iso codes in Geofabrik index file
  - need to create slices or add codes

**Comment by edgar-vincent** [comment]
Thank you very much indeed for having a look at this. There is no rush :)

**Comment by pnoll1** [comment]
FYI, this will  probably be a few more weeks. I'll need to make some code changes to get it working and need to prioritize fixing/improving existing maps first.

**Comment by edgar-vincent** [comment]
Sure! Thanks again so much for having a look at this. There's no rush - I am very grateful you are looking at this at all.

**Comment by pnoll1** [comment]
Files are up in the latest release: https://github.com/pnoll1/osmand_map_creation/releases/tag/1.01. I had to split them into 6 areas so map creator wouldn't crash. 

Please try them out and report anything odd. I'll close this in a week if I don't hear anything.

**Comment by edgar-vincent** [comment]
Thank you so much @pnoll1! It seems to work very so well so far.
