### ISSUE TITLE
All of Northeast Texas is blank/ dead. 

### ISSUE THREAD

**Issue by nerlins** [pnoll1/osmand_map_creation#72]
I've added all of the Texas maps. All four of them. At first I didn't think you're maps worked at all. No addresses I searched for would pull up, then I realized no cities or towns I searched for would pull up. 

When I started zooming in, all of East Texas was completely blank. West and South Texas populate with smaller roads and streets the more you zoom in. When I go to openaddresses I see a bunch of little plotted dots in Northeast Texas. That makes me assume that there is a bunch of address information to be utilized. 

Frankly, I can't type in an address in the open addresses.io site and pull anything up. I'm not really sure how to use that site.

Would you take a look at the Northeast Texas file that you are hosting? Something is going on that is making it show up as blank, and not loading any information into the app. I have started over with a fresh install of OSMand from the Aurora store. I made sure and did not download any maps. The only offline maps were the ones from this project.

It sure would be nice to actually use OSMand like a normal maps app, and this project seems to be the only method. I appreciate you looking into this.

**Comment by pnoll1** [comment]
Slice config is bad. NE and SE file use same coordinates.

I’ll fix and rerun the build

**Comment by nerlins** [comment]
Awesome. Appreciate the quick feedback!

**Comment by pnoll1** [comment]
fixed in f2af46affb0ed1184592df725d31cc072326c194

Sorry about the wait, posted files at https://opensupermaps.com/static/downloads/Us_tx_northeast.obf and https://opensupermaps.com/static/downloads/Us_tx_northwest.obf.

**Comment by nerlins** [comment]
Thanks again. I didn't get a notification of your final response. I'll make sure and download those files today and test it out.
