### ISSUE TITLE
OSMAnd+ not displaying nor finding street (house) addresses

### ISSUE THREAD

**Issue by undrwater** [pnoll1/osmand_map_creation#82]
**Describe the bug**
Loading the map file by clicking on it and selecting OSMAnd should display addresses, but does not even after (de)selecting the map in the app.

**To Reproduce**
Steps to reproduce the behavior, Mention an exact address if possible:
1. Download the latest release (1.06 in this case)
2. Click on the obf that was downloaded
3. (de)select Local maps in the "download maps | local tab
4. Look for house numbers, or generate a search with house numbers, and nothing is generated.

**Expected behavior**
House numbers should display, OR be able to be searched.

**Additional context**
 - OS: crDroid (LIneage OS based), Android 13
Oneplus 8T.

**Comment by pnoll1** [comment]
Map file I'm using looks fine. I'm thinking the loading instructions might be the issue.

When the file was clicked on, did it open in Osmand and load?

When you say:
```(de)select Local maps in the "download maps | local tab```
You only disabled the map file(s) downloaded directly from Osmand?

Did you restart the app by swiping up on it in recent apps then reopening app?

**Comment by undrwater** [comment]
[logcat_osmand.txt](https://github.com/pnoll1/osmand_map_creation/files/13033637/logcat_osmand.txt)
Here's the logcat. There are some interesting lines mentioning failing to load the obf, but not just the Us_ca_south.obf, but the mini world one as well.

**Comment by undrwater** [comment]
There's a file permissions bug for osmand here:
[https://github.com/osmandapp/OsmAnd/issues/18352](url)

Could it be related?

**Comment by undrwater** [comment]
I'm going to close this with your permission.

The issue was an assumption of area. I live in Southern California, so I assumed Us_ca_south was the correct file. It wasn't. The correct one was Us_ca_southcentral.

Thanks!

PS: Maybe a description of coverage area with the maps could be useful. I'd be willing to help.

**Comment by pnoll1** [comment]
Glad you got it figured out.

Yeah...those filenames aren't very descriptive. I brainstormed some options on the linked issue above for helping that. If you've got any thoughts, feel free to chime in on that issue. Always nice to have another set of eyes.
